id: 
name: GitOps.BreakingChangeIssue
description: GitOps.BreakingChangeIssue primitive
owner: 
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
    - description: '[10-10] Add breaking change doc instructions to issue'
      if:
      - payloadType: Issues
      - labelAdded:
          label: breaking-change
      then:
      - addReply:
          reply: >-
            For changes in NuGet functionality (such as NuGet Restore changes), refer to the [.NET SDK breaking change guidelines](https://github.com/dotnet/sdk/blob/main/documentation/project-docs/breaking-change-guidelines.md#required-process-for-all-net-sdk-breaking-changes)
onFailure: 
onSuccess: 
