name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["Type:Bug", "Triage:Untriaged"]
body:
  - type: markdown
    value: |
      Thank you for taking the time to file this issue. In order to resolve it, we just need a few details from you.
      
      The more detail you provide, the more likely it will be for us to be able to identify what is going on and how to solve it!
  - type: dropdown
    id: product
    attributes:
      label: NuGet Product Used
      multiple: true
      description: Which of our NuGet clients does this apply to?
      options:
        - NuGet.exe
        - Visual Studio Package Management UI
        - Visual Studio Package Manager Console
        - MSBuild.exe
        - dotnet.exe
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Product Version
      description: Which software version does this apply to?
      placeholder: dotnet --info, msbuild -version, nuget.exe ?, etc
    validations:
      required: true
  - type: checkboxes
    id: regression
    attributes:
      label: Worked Before?
      description: Is this a regression? Did it work in a previous version?
      options:
        - label: This used to work.
    validations:
      required: false
  - type: input
    id: lastworking
    attributes:
      label: Which Version?
      description: If so, what was the last working version?
    validations:
      required: false
  - type: textarea
    id: repro
    attributes:
      label: Repro Steps
      description: What steps can the NuGet team take to reproduce this issue?
      placeholder: |
        Please add as much detail as possible to help us to reproduce your problem.

        1. step one
        2. step two
        3. ...
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: Expected
      description: What did you expect to see happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual
      description: What happened instead?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Verbose Logs
      description: If possible, please include verbose logs of the issue.
      placeholder: NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...
      render: shell
    validations:
      required: false
