name: Behavior Change
description: When you want NuGet to work differently than it does.
labels: ["Type:DCR", "Triage:Untriaged"]
body:
  - type: markdown
    attributes:
      value: |
       Thank you for taking the time to file this issue. In order to best understand what you're asking and what your needs are, we just need a few details from you.
       
       Please note that designs are usually affected by our own product development processes, and we can't guarantee any particular timeline for when this change might be made.
       
       Additionally, keep in mind that Design Change Requests like this one might involve a breaking change, and if it's significant enough, or if it clashes with other product plans, we might have to turn it down. This is more a reflection of our processes and requirements rather than your particular request, so your understanding is appreciated.
  - type: dropdown
    id: product
    attributes:
      label: NuGet Product(s) Affected
      multiple: true
      description: Which of our NuGet clients does this apply to?
      options:
        - NuGet.exe
        - Visual Studio Package Management UI
        - Visual Studio Package Manager Console
        - MSBuild.exe
        - dotnet.exe
        - NuGet SDK
        - Other/NA
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Current Behavior
      description: Please describe, in your own words, how you think things currently work now.
    validations:
      required: true
  - type: textarea
    id: desired
    attributes:
      label: Desired Behavior
      description: What do you think should happen instead?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context you want to share about this. Why is it important to you? What do other tools do? etc.
    validations:
      required: false
