name: Behavior Change
description: When you want NuGet to work differently than it does.
title: "[DCR]: "
labels: ["Type:DCR", "Triage:Untriaged"]
body:
  - type: dropdown
    id: product
    attributes:
      label: NuGet Product(s) Affected
      multiple: true
      description: Which of our NuGet clients does this apply to?
      options:
        - NuGet.exe
        - Visual Studio Package Management UI
        - Visual Studio Package Manager Console
        - MSBuild.exe
        - dotnet.exe
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Current Behavior
      description: Please describe, in your own words, how you think things currently work now.
    validations:
      required: true
  - type: textarea
    id: desired
    attributes:
      label: Desired Behavior
      description: What do you think should happen instead?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context you want to share about this. Why is it important to you? What do other tools do? etc.
    validations:
      required: false
