name: Feature Request
description: "When you want a new feature for something that doesn't already exist"
title: "[Feature]: "
labels: ["Type:Feature", "Triage:Untriaged"]
body:
  - type: dropdown
    id: product
    attributes:
      label: NuGet Product(s) Involved
      multiple: true
      description: Which of our NuGet clients does this apply to?
      options:
        - NuGet.exe
        - Visual Studio Package Management UI
        - Visual Studio Package Manager Console
        - MSBuild.exe
        - dotnet.exe
    validations:
      required: true
  - type: textarea
    id: desired
    attributes:
      label: The Elevator Pitch
      description: Pitch us the feature! What can NuGet do better for you?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context and Details
      description: Any other context or details you want to share about this. Why is it important to you? What do other tools do? etc.
    validations:
      required: false
