name: Bug Report
description: File a bug report.
body:
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      options:
        - Bug
        - Feature
    validations:
      required: true
  - type: input
    id: bug-details
    attributes:
      label: Bug Details
    if: issue-type == 'Bug'
