name: IceBox Upvote Watcher
on:
  # Run before 9am Seattle time, so discussion needed labels are added before the working day.
  # Run at non-zero minute so we're not running at the same time as everyone else who runs at the zero minute
  schedule:
    - cron: '34 13 * * *'
  # Allow manual triggering, so testing changes is easier
  workflow_dispatch:
    inputs:
      entrypyBranch:
        description: 'The Entropy repo branch to use'
        required: true
        default: 'main'
      LabelToCheck:
        description: 'The label to check for upvotes'
        required: true
        default: 'Priority:3'
      Upvotes:
        description: 'Upvote threshold'
        required: true
        type: number
        default: 5
      AddOnThreshold:
        description: 'Add label when threshold is reached'
        required: true
        type: boolean
        default: false
      LabelToAdd:
        description: 'The label to add to the upvoted issue'
        required: true
        default: 'Triage:NeedsTriageDiscussion'

permissions:
  issues: write

jobs:
  Run-IceBox-Watcher:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Clone Entropy
        env:
          BRANCH: ${{ inputs.entrypyBranch || 'main' }}
        run: |
          git clone https://github.com/NuGet/Entropy
          git -C Entropy switch $BRANCH

      - name: Install Latest .NET SDK
        run: |
          curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --install-dir $HOME/dotnet
          dotnet --info

      - name: Build GitHubIssueTagger
        working-directory: Entropy/GithubIssueTagger
        run: |
          dotnet build

      - name: Run IceBox Watcher
        env:
          # The defaults on the workflow_dispatch don't apply to the scheduled trigger.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL_TO_CHECK: ${{ inputs.LabelToCheck || 'Priority:3' }}
          UPVOTE_THRESHOLD: ${{ inputs.Upvotes || 5 }}
          ADD_ON_THRESHOLD: ${{ inputs.AddOnThreshold || true }}
          LABEL_TO_ADD: ${{ inputs.LabelToAdd || 'Triage:NeedsTriageDiscussion' }}
        working-directory: Entropy/GithubIssueTagger
        run: |
          if $ADD_ON_THRESHOLD; then
            dotnet run -- IceBox --label $LABEL_TO_CHECK --upvotes $UPVOTE_THRESHOLD --add $LABEL_TO_ADD
          else
            dotnet run -- IceBox --label $LABEL_TO_CHECK --upvotes $UPVOTE_THRESHOLD
          fi
